# Generated by Django 2.1.3 on 2018-11-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_advert_numberofviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='owner',
            new_name='created_by',
        ),
    ]
