# Generated by Django 2.1.3 on 2018-11-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181125_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='rest',
            new_name='restaurant',
        ),
    ]
