# Generated by Django 2.1.3 on 2018-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reviews'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='created_by',
        ),
    ]
