# Generated by Django 2.1.3 on 2018-11-25 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181125_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
