# Generated by Django 2.1.3 on 2018-11-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_receipt_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='com_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Receipt'),
        ),
    ]
