# Generated by Django 2.1.3 on 2018-11-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181126_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Receipt'),
        ),
    ]
